# Generated by Django 4.2.2 on 2023-07-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
