# Generated by Django 4.2.2 on 2023-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0004_profile_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
